# Generated by Django 3.2 on 2021-06-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0004_order_event_desire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_desire',
            field=models.CharField(choices=[('cuisine', 'cuisine'), ('event planning', 'event planning'), ('Aso ebi', 'Aso ebi')], default='cuisine', max_length=100),
        ),
    ]
